// biome-ignore-all lint: gen

/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebookIdRouteImport } from './routes/notebook.$id'
import { Route as NotebookIdEditorRouteImport } from './routes/notebook.$id_.editor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIdRoute = NotebookIdRouteImport.update({
  id: '/notebook/$id',
  path: '/notebook/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIdEditorRoute = NotebookIdEditorRouteImport.update({
  id: '/notebook/$id_/editor',
  path: '/notebook/$id/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/notebook/$id/editor': typeof NotebookIdEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/notebook/$id/editor': typeof NotebookIdEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/notebook/$id_/editor': typeof NotebookIdEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notebook/$id' | '/notebook/$id/editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notebook/$id' | '/notebook/$id/editor'
  id: '__root__' | '/' | '/notebook/$id' | '/notebook/$id_/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotebookIdRoute: typeof NotebookIdRoute
  NotebookIdEditorRoute: typeof NotebookIdEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/$id': {
      id: '/notebook/$id'
      path: '/notebook/$id'
      fullPath: '/notebook/$id'
      preLoaderRoute: typeof NotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/$id_/editor': {
      id: '/notebook/$id_/editor'
      path: '/notebook/$id/editor'
      fullPath: '/notebook/$id/editor'
      preLoaderRoute: typeof NotebookIdEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotebookIdRoute: NotebookIdRoute,
  NotebookIdEditorRoute: NotebookIdEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
